name: CI

on:
  push:
    branches: [ master ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
      fail-fast: false


    steps:
      - uses: actions/checkout@v2

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: '.'
          extensions: 'h,cpp'
          clangFormatVersion: 9
        if: matrix.os == 'ubuntu-20.04'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        if: matrix.os == 'ubuntu-20.04'

      - name: Install dependencies (Linux)
        run: ./scripts/install_linux_deps.sh
        if: matrix.os == 'ubuntu-20.04'

      - name: Install dependencies (Mac OS)
        run: ./scripts/install_osx_deps.sh
        if: matrix.os == 'macos-10.15'

      - name: Run tests
        run: ./scripts/run_cpp_tests.sh
